### ISSUE TITLE
Cannot reinstall KFD cluster on same VMs after deleting it with 'furyctl delete cluster'

### ISSUE THREAD

**Issue by woopla** [sighupio/fury-kubernetes-networking#80]
Not sure if this is a `furyctl` issue, a networking module one, or a problem between the keyboard and the chair :)

If was able to create a KFD cluster using Calico. I'm now trying to create one with Cilium, but it's failing to install and times out waiting to get a bootstrap token. Looking at the Kubelet logs on the control plane host, I see 'cni plugin not initialized' errors. There's no `/etc/cni` directory on the host.

Here's an excerpt of my `furyctl.yaml` file:

```yaml
spec:
  kubernetes:
    podCidr: 172.16.128.0/17
    svcCidr: 172.16.0.0/17
  distribution:
    modules:
      networking:
        type: cilium
```

Is there anything else that I should be setting in the YAML file for Cilium?

**Comment by ralgozino** [comment]
Hi Woopla,

Which versions are you using (furyctl and distribution)?

Are you using by anychance a VM on VMware with a `VMXNet` NIC? If that's the case you'll need to disable "hardware segmentation offload" in the VMs, [Cilium has issues with that option enabled](https://github.com/cilium/cilium/issues/21801).

You can disable it with the following commands:

```bash
sudo ethtool -K ens192 tx-udp_tnl-segmentation off
sudo ethtool -K ens192 tx-udp_tnl-csum-segmentation off
```

**Comment by woopla** [comment]
OK now I'm thinking that _something_ was not properly cleaned up when I deleted the Calico-based cluster on the same set of VMs. I've tried re-installing with the same Calico-based YAML file, and it's still not working. Here's my cleanup script:

```bash
furyctl delete cluster --outdir "$PWD" || true

p1_script=$(mktemp)
cat <<EOF > "$p1_script"
#!/bin/bash -e

systemctl stop kubelet
(find /var/lib/kubelet 2>/dev/null || true) | xargs --no-run-if-empty -n 1 findmnt -n -t tmpfs -o TARGET -T \
    | uniq | xargs -r umount -v
rm -rf /etc/kubernetes /var/lib/kubelet /var/lib/etcd

# See https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/troubleshooting-cni-plugin-related-errors/
mkdir -p /etc/cni/net/
echo <<EOF2 > /etc/cni/net/10-containerd-net.conflist
{
 "cniVersion": "1.0.0",
 "name": "containerd-net",
 "plugins": [
   {
     "type": "bridge",
     "bridge": "cni0",
     "isGateway": true,
     "ipMasq": true,
     "promiscMode": true,
     "ipam": {
       "type": "host-local",
       "ranges": [
         [{
           "subnet": "10.88.0.0/16"
         }],
         [{
           "subnet": "2001:db8:4860::/64"
         }]
       ],
       "routes": [
         { "dst": "0.0.0.0/0" },
         { "dst": "::/0" }
       ]
     }
   },
   {
     "type": "portmap",
     "capabilities": {"portMappings": true},
     "externalSetMarkChain": "KUBE-MARK-MASQ"
   }
 ]
}
EOF2

EOF

p2_script=$(mktemp)
cat <<EOF > "$p2_script"
#!/bin/bash -e

crictl rmp --force -a && kubeadm reset --force
crictl rmi --prune --all
ipvsadm --clear
iptables -F && iptables -X
iptables -t nat -F && iptables -t nat -X
iptables -t raw -F && iptables -t raw -X
iptables -t mangle -F && iptables -t mangle -X
rm -rf /etc/cni/ ~/.kube /var/lib/cni/

EOF

chmod a+rx "$p1_script" "$p2_script"

while read -r hostname; do
    (
    ssh -n "root@$hostname" "/net/$(hostname -f)/$p1_script"
    ssh -n "root@$hostname" /sbin/reboot || true
    sleep 30
    ssh -n "root@$hostname" "/net/$(hostname -f)/$p2_script"
    ) &
done <<<"$(yq -r '.spec.kubernetes | .masters, .nodes[0] | .hosts | .[].name' < "furyctl.yaml")"

wait

rm -f "$p1_script" "$p2_script"
```


Just running `furyctl delete` was not enough and `kubeadm reset` was unable to properly clean everything, hence this complexity...

**Comment by ralgozino** [comment]
hi @woopla 

let me see check that I got it right:

1. You installed first using Calico as CNI.
2. Ran `furyctl delete` to clean up the machines.
3. Reinstalled using Cilium but it did not success.
4. You cleaned up manually the machines
5. Installing after the clean up with Cilium is working now. 

is the previous correct?

would you mind giving us some steps to try to reproduce the issue? we might be missing something on the `delete` process.

cc @Al-Pragliola for awareness

**Comment by woopla** [comment]
Hey @ralgozino ,

I wish Point 5 was right 😅  I still cannot recreate a cluster on the same set of VMs, even after running the cleanup script above. I reverted back to Calico, thinking that Cilium was the issue (I'm running on Rocky 8.6 and I'm thinking I should move to 9.x, even though that's not full-production in our environment just yet).

But even with the exact same `furyctl.yaml` file that worked the first time around, no luck. I'd like to understand what is preventing things from starting, but I don't know where to look. As you can see in the script, I'm deleting the pods, the images, `/etc/cni`.... Should I maybe also check for additional network interfaces that "look like" Kubernetes ones, and delete these?

**Comment by woopla** [comment]
Here's a sanitized version of my `furyctl.yaml`:

```yaml

# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kfd.sighup.io/v1alpha2
kind: OnPremises
metadata:
  name: XXXX
spec:
  distributionVersion: v1.29.1
  kubernetes:
    pkiFolder: ./pki
    ssh:
      username: root
      keyPath: ~/.ssh/id_rsa
    dnsZone: site.bigcorp.com
    controlPlaneAddress: XXXk8s-ctrl.site.bigcorp.com:6443
    podCidr: 172.16.128.0/17
    svcCidr: 172.16.0.0/17
    loadBalancers:
      enabled: true
      hosts:
        - name: XXXk8s-lb01
          ip: 10.102.84.148
        - name: XXXk8s-lb02
          ip: 10.102.82.228
      keepalived:
        enabled: true
        interface: ens192
        ip: 10.102.83.47
        virtualRouterId: "201"
        passphrase: "b16cf069"
      stats:
        username: admin
        password: password
      additionalConfig: "{file://./haproxy-additional.cfg}"
    masters:
      hosts:
        - name: XXXk8s-cp01
          ip: 10.102.83.28
        - name: XXXk8s-cp02
          ip: 10.102.82.81
        - name: XXXk8s-cp03
          ip: 10.102.82.59
    nodes:
      - name: worker
        hosts:
          - name: XXXk8s-wk01
            ip: 10.253.19.157
          - name: XXXk8s-wk02
            ip: 10.252.148.179
  distribution:
    common: {}
    modules:
      networking:
        type: calico
      # This section contains all the configurations for the ingress module
      ingress:
        baseDomain: group.site.bigcorp.com
        nginx:
          type: single
          tls:
            provider: secret
            secret:
              cert: "{file://./pki/tls/tls.crt}"
              key: "{file://./pki/tls/tls.key}"
              ca: "{file://./pki/tls/ca.crt}"
        certManager:
          clusterIssuer:
            name: letsencrypt-fury
            email: example@sighup.io
            type: http01
      logging:
        type: loki
        minio:
          storageSize: "10Gi"
      monitoring:
        type: prometheus
      policy:
        type: none
      dr:
        type: on-premises
        velero: {}
      auth:
        provider:
          type: none 
        
  plugins:
    kustomize: 
      - name: cert-manager-secret
        folder: ./cert-manager-secret/
      - name: storage
        folder: https://github.com/rancher/local-path-provisioner/deploy?ref=v0.0.24
    helm:
        repositories:
          - name: nfs-subdir-external-provisioner
            url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
          - name: portainer
            url: https://portainer.github.io/k8s
        releases:
          - name: nfs-subdir-external-provisioner
            namespace: nfs-subdir-external-provisione
            chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
            set:
              - name: nfs.server
                value: XXXX.site.bigcorp.com
              - name: nfs.path
                value: XXXXXX
          - name: portainer
            namespace: portainer
            chart: portainer/portainer
            set:
              - name: image.repository
                value: portainer/portainer-ee
              - name: service.type
                value: ClusterIP
              - name: enterpriseEdition.enabled
                value: "true"
              - name: ingress.enabled
                value: "true"
              - name: ingress.hosts[0].host
                value: portainer.group.site.bigcorp.com
              - name: ingress.tls[0].hosts[0]
                value: portainer.group.site.bigcorp.com
              - name: ingress.hosts[0].paths[0].path
                value: /

```

**Comment by ralgozino** [comment]
Hi @woopla , what is the error you get when the bootstrap goes in timeout?

have you tried running `kubeadm` manually to see if you get more details?

**Comment by woopla** [comment]
Here's the relevant output @ralgozino:

```
TASK [kube-control-plane : Initializing master] ********************************
fatal: [XXXk8s-cp01]: FAILED! => changed=true 
  cmd:
  - kubeadm
  - init
  - --config=/etc/kubernetes/kubeadm.yml
  delta: '0:02:36.696336'
  end: '2024-06-17 22:13:44.029739'
  msg: non-zero return code
  rc: 1
  start: '2024-06-17 22:11:07.333403'
  stderr: |-
    W0617 22:11:42.827350   75467 checks.go:835] detected that the sandbox image "k8s.gcr.io/pause:3.2" of the container runtime is inconsistent with that used by kubeadm. It is recommended that using "registry.sighup.io/fury/on-premises/pause:3.9" as the CRI sandbox image.
    error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
    To see the stack trace of this error execute with --v=5 or higher
  stderr_lines: <omitted>
  stdout: |-
    [init] Using Kubernetes version: v1.29.3
    [preflight] Running pre-flight checks
    [preflight] Pulling images required for setting up a Kubernetes cluster
    [preflight] This might take a minute or two, depending on the speed of your internet connection
    [preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
    [certs] Using certificateDir folder "/etc/kubernetes/pki"
    [certs] Using existing ca certificate authority
    [certs] Generating "apiserver" certificate and key
    [certs] apiserver serving cert is signed for DNS names [kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local XXXk8s-cp01.site.bigcorp.com XXXk8s-ctrl.site.bigcorp.com] and IPs [172.16.0.1 10.102.83.28]
    [certs] Generating "apiserver-kubelet-client" certificate and key
    [certs] Using existing front-proxy-ca certificate authority
    [certs] Generating "front-proxy-client" certificate and key
    [certs] External etcd mode: Skipping etcd/ca certificate authority generation
    [certs] External etcd mode: Skipping etcd/server certificate generation
    [certs] External etcd mode: Skipping etcd/peer certificate generation
    [certs] External etcd mode: Skipping etcd/healthcheck-client certificate generation
    [certs] External etcd mode: Skipping apiserver-etcd-client certificate generation
    [certs] Using the existing "sa" key
    [kubeconfig] Using kubeconfig folder "/etc/kubernetes"
    [kubeconfig] Writing "admin.conf" kubeconfig file
    [kubeconfig] Writing "super-admin.conf" kubeconfig file
    [kubeconfig] Writing "kubelet.conf" kubeconfig file
    [kubeconfig] Writing "controller-manager.conf" kubeconfig file
    [kubeconfig] Writing "scheduler.conf" kubeconfig file
    [control-plane] Using manifest folder "/etc/kubernetes/manifests"
    [control-plane] Creating static Pod manifest for "kube-apiserver"
    [control-plane] Creating static Pod manifest for "kube-controller-manager"
    [control-plane] Creating static Pod manifest for "kube-scheduler"
    [kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
    [kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
    [kubelet-start] Starting the kubelet
    [wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
    [kubelet-check] Initial timeout of 40s passed.
    [kubelet-check] It seems like the kubelet isn't running or healthy.
    [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.
    [kubelet-check] It seems like the kubelet isn't running or healthy.
    [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.
    [kubelet-check] It seems like the kubelet isn't running or healthy.
    [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.
    [kubelet-check] It seems like the kubelet isn't running or healthy.
    [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.
    [kubelet-check] It seems like the kubelet isn't running or healthy.
    [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.
  
    Unfortunately, an error has occurred:
            timed out waiting for the condition
  
    This error is likely caused by:
            - The kubelet is not running
            - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
  
    If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
            - 'systemctl status kubelet'
            - 'journalctl -xeu kubelet'
  
    Additionally, a control plane component may have crashed or exited when started by the container runtime.
    To troubleshoot, list all containers using your preferred container runtimes CLI.
    Here is one example how you may list all running Kubernetes containers by using crictl:
            - 'crictl --runtime-endpoint unix:///var/run/containerd/containerd.sock ps -a | grep kube | grep -v pause'
            Once you have found the failing container, you can inspect its logs with:
            - 'crictl --runtime-endpoint unix:///var/run/containerd/containerd.sock logs CONTAINERID'
  stdout_lines: <omitted>

```

I just tried to run `kubeadm init --config=/etc/kubernetes/kubeadm.yml` but it failed during the pre-flight checks, I suppose because there's already a (unhealthy) kubelet running.

Here are the contents of `/etc/kubernetes/kubeadm.yml`:

```yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  name: XXXk8s-cp01.site.bigcorp.com
  kubeletExtraArgs:
    cloud-provider: 
localAPIEndpoint:
  advertiseAddress: 10.102.83.28
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
etcd:
  external:
    endpoints:
    - https://127.0.0.1:2379

    caFile: /etc/etcd/pki/etcd/ca.crt
    certFile: /etc/etcd/pki/apiserver-etcd-client.crt
    keyFile: /etc/etcd/pki/apiserver-etcd-client.key
clusterName: XXXX
kubernetesVersion: 1.29.3
imageRepository: "registry.sighup.io/fury/on-premises"
controlPlaneEndpoint: XXXk8s-ctrl.site.bigcorp.com:6443
dns:
  imageRepository: registry.sighup.io/fury/on-premises/coredns
apiServer:
  extraArgs:
    enable-admission-plugins: "NamespaceLifecycle,LimitRanger,PodNodeSelector,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
    cloud-provider: 
    audit-log-maxage: "3"
    audit-log-path: "/var/log/kubernetes/kube-apiserver-audit.log"
    audit-policy-file: /etc/kubernetes/audit.yaml
    audit-log-maxsize: "50"
    audit-log-maxbackup: "20"
  extraVolumes:
  - name: audit-files
    hostPath: /var/log/kubernetes
    mountPath: /var/log/kubernetes
    readOnly: false
    pathType: Directory
  - name: audit-policy
    hostPath: /etc/kubernetes/audit.yaml
    mountPath: /etc/kubernetes/audit.yaml
    readOnly: true
    pathType: File
  timeoutForControlPlane: 4m0s
scheduler:
  extraArgs:
    bind-address: 10.102.83.28
controllerManager:
  extraArgs:
    bind-address: 10.102.83.28
    cloud-provider: 
networking:
  podSubnet: 172.16.128.0/17
  serviceSubnet: 172.16.0.0/17
  dnsDomain: "cluster.local"
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: 0.0.0.0
clusterCIDR: "172.16.128.0/17"
ipvs:
  excludeCIDRs: null
  minSyncPeriod: 0s
  scheduler: ""
  syncPeriod: 30s
metricsBindAddress: 0.0.0.0:10249
mode: ipvs
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd

```
