### ISSUE TITLE
No ingress installed for Cilium Hubble

### ISSUE THREAD

**Issue by woopla** [sighupio/fury-kubernetes-networking#81]
When installing Cilium, the Hubble observability tool is also installed in the cluster, but there's no ingress to access it. I copied the Grafana one and made the necessary adjustments, but I think this should be done by default. Something like:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cluster.kfd.sighup.io/useful-link.name: Cilium Hubble UI
    cluster.kfd.sighup.io/useful-link.url: https://cilium-hubble.XXXXXX
    forecastle.stakater.com/appName: Cilium Hubble
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: https://cilium.io/static/hubble-light-1-812e65cbb72a7f4efed59fcea48df840.svg
  labels:
    cluster.kfd.sighup.io/useful-link.enable: "true"
  name: hubble-ui
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
  - host: cilium-hubble.XXXXXX
    http:
      paths:
      - backend:
          service:
            name: hubble-ui
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - cilium-hubble.XXXXXX

```
